INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (1)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (2)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (3)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (4)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (5)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (6)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (7)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (8)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (9)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (10)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (11)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (12)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (13)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (14)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (15)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (16)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (17)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (18)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (19)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (20)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (21)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (22)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (23)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (24)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (25)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (26)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (27)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (28)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (29)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (30)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (31)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (32)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (33)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (34)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (35)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (36)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (37)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (38)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (39)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (40)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (41)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (42)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (43)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (44)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (45)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (46)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (47)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (48)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (49)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (50)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (51)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (52)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (53)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (54)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (55)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (56)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (57)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (58)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (59)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (60)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (61)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (62)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (63)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (64)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (65)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (66)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (67)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (68)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (69)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (70)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (71)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (72)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (73)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (74)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (75)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (76)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (77)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (78)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (79)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (80)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (81)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (82)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (83)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (84)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (85)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (86)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (87)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (88)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (89)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (90)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (91)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (92)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (93)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (94)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (95)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (96)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (97)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (98)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (99)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (100)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (101)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (102)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (103)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (104)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (105)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (106)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (107)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (108)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (109)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (110)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (111)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (112)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (113)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (114)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (115)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (116)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (117)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (118)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (119)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (120)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (121)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (122)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (123)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (124)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (125)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (126)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (127)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (128)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (129)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (130)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (131)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (132)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (133)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (134)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (135)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (136)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (137)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (138)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (139)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (140)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (141)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (142)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (143)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (144)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (145)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (146)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (147)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (148)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (149)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (150)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (151)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (152)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (153)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (154)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (155)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (156)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (157)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (158)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (159)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (160)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (161)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (162)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (163)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (164)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (165)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (166)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (167)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (168)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (169)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (170)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (171)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (172)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (173)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (174)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (175)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (176)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ البريك في رمضان (177)؟', 'شنوّة أكثر أكلة رمضانية تحبّها؟', 'traditions', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (178)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (179)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (180)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (181)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (182)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الجو متاع الصيف ولا الشتاء (183)؟', 'شنوّة الموسم المفضل عندك؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (184)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (185)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (186)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (187)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (188)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('وين تحبّ تخرج في الويكاند (189)؟', 'تحبّ تبقى في الدار ولا تخرج؟', 'daily_life', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (190)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (191)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ المهرجانات التونسية (192)؟', 'آخر مرّة مشيت فيها لمهرجان وقتاش؟', 'culture', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (193)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (194)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ تشرب القهوة ولا القاطو أكثر (195)؟', 'من غير ما تفكر، قهوة ولا عصير؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكرة (196)؟', 'فما فريق تحبّو برشة؟', 'sports', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('أخر مرّة مشيت للبحر وقتاش (197)؟', 'تحبّ البحر ولا الجبل أكثر؟', 'places', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر فنان تونسي تسمعلو (198)؟', 'تحبّ الموسيقى التونسية القديمة ولا الجديدة؟', 'music', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('شنوّة أكثر أكلة تونسية تحبّها (199)؟', 'تحبّ الماكلة التونسية ولا لا؟', 'food', 'ar-TN');
INSERT INTO question (text, alt_text, category, locale) VALUES ('تحبّ الكسكسي باللّحم ولا بالدجاج (200)؟', 'شنوّة طريقتك المفضّلة في الكسكسي؟', 'food', 'ar-TN');